    - name: Create a network
      become: yes
      become_method: sudo
      docker_network:
        name: docker_CD
        state: present

    - name: Create a web-app container 
      become: yes 
      become_method: sudo
      docker_container:
        name: "web-app{{ item }}"
        recreate: yes
        image: shlepanets/epam-exam:exam-im-latest
        ports:
          - "500{{ item}}:5000"
        networks: docker_CD
      with_sequence: count=3
